# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Build
      run: go build -o lox-interpreter app/*.go

    - name: Test
      run: |
        echo 'print "Hello, World!";' > test.lox
        ./lox-interpreter run test.lox

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      if: github.ref == 'refs/heads/dev'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./web
        publish_branch: gh-pages
